modLoader="javafml"
loaderVersion="[40,)"
license="LGPLv2.1"
issueTrackerURL="https://github.com/smashingmods/alchemylib/issues"

[[mods]]
modId="alchemylib"
version="${file.jarVersion}"
displayName="AlchemyLib"
logoFile="alchemylib-logo.png"
authors="SmashingMods"
description='''
AlchemyLib is a library mod for ChemLib addon mods such as Alchemistry and Techemistry. Anyone can use AlchemyLib to help bootstrap their mod development. Everything you need is in the api package.
'''

[[dependencies.alchemylib]]
modId="forge"
mandatory=true
versionRange="[40.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.alchemylib]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.alchemylib]]
modId="chemlib"
mandatory=true
versionRange="[1.18.2-2.0.16,)"
ordering="NONE"
side="BOTH"