modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv2.1"
issueTrackerURL="https://github.com/smashingmods/alchemylib/issues"

[[mods]]
modId="alchemylib"
version="${file.jarVersion}"
displayName="AlchemyLib"
logoFile="alchemylib-logo.png"
authors="SmashingMods"
description='''
AlchemyLib contains shared code for machines and screens.
'''

[[dependencies.alchemylib]]
modId="forge"
mandatory=true
versionRange="[43.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.alchemylib]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.alchemylib]]
modId="chemlib"
mandatory=true
versionRange="[1.19.2-2.0.13,)"
ordering="NONE"
side="BOTH"